default: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password: 
  host: localhost
  pool: 5

development:
  <<: *default
  database: tunein_development

test:
  <<: *default
  database: tunein_test

production:
  <<: *default
  database: tunein_production